version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=${MONGODB_URI}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-vehicle-data}
      - KAFKA_CONSUMER_GROUP=${KAFKA_CONSUMER_GROUP:-insurance-group}
      - JAVA_OPTS=-Xms512m -Xmx1024m
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3 